title: Can i Run?
logo: /assets/img/logo.jpg
description: Fresh and reliable information regarding the quality of air in the city of Tbilisi (Georgia) 
show_downloads: false 
google_analytics:
theme: jekyll-theme-minimal
